package br.edu.iftm.excecao.erros;

public class Matematica {
    public void divisao(int numeroA, int numeroB) throws Exception{
       // try {
            System.out.println(numeroA/numeroB);
       /* } catch (Exception e) {
            System.out.println("Houve um erro durante a divis√£o");
            System.out.println(e.getMessage());
        }*/
        
    }
    
}
